name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - awscli
  - boto3
  - ipykernel
  - pyspark=3.0.2
  - setuptools
  - numpy=1.19.1
  - scipy=1.5.2
  - scikit-learn=0.23
  - pandas=1.1
  - pillow=8.1.2
  - python-dateutil=2.8.1
  - requests=2.24.0
  - svgwrite=1.4
  - scikit-image=0.19.0
  - imutils=0.5.4
  - wheel
  - fastapi=0.70.1
  - uvicorn=0.16
  - wget
