version: '3'

services:
        spark:
                image: zeroshotapp
                build:
                       context: ./
                       dockerfile: Dockerfile
                container_name: zeroshotapp
                volumes:
                        - ./prompts:/home/jsl/prompts
                environment:
                        - SPARK_MODE=master
                        - STREAMLIT_SERVER_HEADLESS=true
                        - cores=1
                        - spark.driver.memory=8G
                ports:
                        - 8501:8501
                        - 8888:8888